Add test reporting to cmake github workflow

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -23,12 +23,12 @@ jobs:
 
     - name: Test
       working-directory: ${{github.workspace}}/build
-      run: ctest
+      run: ctest --output-junit testReport.xml
       
-    - name: Generate test report
-      uses: mikepenz/action-junit-report@v3.8.0
-
-    - name: Display test report
-      uses: turing85/publish-report@v1.0.11
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
       with:
-        comment-header: CTest Report
+        name: JEST Tests            # Name of the check run which will be created
+        path: *.xml    # Path to test results
+        reporter: jest-junit        # Format of test results
